name: brokali
description: Shopping list

version: 0.2.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  flutter_calendar_carousel: any
  flutter_launcher_icons: any
  bloc: ^0.11.0
  flutter_bloc: ^0.9.0
  meta: ^1.1.6
  equatable: ^0.1.6
  rxdart: ^0.21.0
  path_provider: ^0.5.0+1
  uuid: ^2.0.0
  http: any
  firebase_auth: ^0.8.1+1
  cloud_firestore: ^0.9.0+2
  shared_preferences: ^0.5.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/icon512.png" 
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/i18n/categories/
    - assets/i18n/general/
    - assets/i18n/products/
    